### ISSUE TITLE
List all barnard packages

### ISSUE THREAD

**Issue by magdasalatka** [zazuko/barnard59-docs#7]
List all BARNARD59 packages, and write it to markdown file

https://api.github.com/users/zazuko/repos

**Comment by bergos** [comment]
The list should not be fixed to a specific org and package pattern. If other people publish useful packages, it should be possible to include them in the list. I guess most people would view the overview on the web. I would propose to create a separate repo or branch with a curated list. We could also include scripts to convert the markdown to html for a gh page. The package + git/version history would have a clear scope: barnard59-docs is a generic doc generator like jsdocs, the curated list contains the overview and git commits may just be triggers to update the content.

**Comment by tpluscode** [comment]
What about finding packages directly on npm by a tag and generating the docs automatically, say once a day, to update the docs list?

**Comment by bergos** [comment]
@tpluscode why easy if it can be done complicated? To change the content in package a, package b needs to be changed? That would also mean, that anyone can change the content in package a, by including a tag in any other package. At the end we have to maintain a list of packages we want to exclude.

Wouldn't it be more obvious to maintain a list in package a of packages that should be included? That would also allow to add sections and define the order of their appearance. All that would be maintained next to the generated docs, which is also the first place where you would look if a package you expected to be included doesn't show up.

**Comment by ludovicm67** [comment]
I don't know exactly why I was assigned to this, but I would suggest having a simple file with the list that we maintain would be the way to go. Others can also contribute by submitting PR. Efficient, contributory and keep the whole simple.
Having a thing that takes this file, probably a Markdown one, and renders it as HTML with a nice template is something we can do, and I would be happy to help for this. Easy for people to add new entries (a simple Markdown file), and having a nice static web page that we can host on GitHub Pages.

We don't have the resources to maintain a wired thing that behaves like a "spider", then maintain filters to avoid spam issues, … I will not go in this direction.

**Comment by ludovicm67** [comment]
I've created this repo: https://github.com/zazuko/barnard59-website as a start
It's the source code for https://barnard59.zazuko.com/

You can add a new list of packages by creating a new file in this directory: https://github.com/zazuko/barnard59-website/tree/main/lists
You can edit packages that are listed on a specific list by editing the corresponding file in this `lists` directory.

The mechanism to fetch data about packages is inspired by this repo (https://github.com/zazuko/barnard59-docs), but for both of them I can see some `undefined` values, like here: https://barnard59.zazuko.com/package/official/barnard59-core
